language: node_js
node_js:
  - "node"
  - "lts/*"

# migrate to travis' new container infrastructure
sudo: true
install:
  - npm install
  - npm install -g ejs-cli
  - npm -g install embark
  - npm install web3
script:
  - screen -d -m embark blockchain
  - ./do
  - embark build
after_script:
  - killall geth
